name: flutter_sixvalley_ecommerce
description: A Flutter eCommerce application.

publish_to: 'none'
version: 2.0.15+15

environment:
  sdk: '^3.2.1'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  provider: ^6.1.2
  connectivity_plus: ^4.0.1
  dio: ^5.4.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  webview_flutter: ^4.7.0
  flutter_html: ^3.0.0-beta.2
  share_plus: ^7.2.2
  photo_view: ^0.14.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  # flutter_local_notifications: ^14.1.5
  path_provider: ^2.1.2
  google_sign_in: 6.1.6
  flutter_facebook_auth: ^6.1.1
  flutter_svg: ^2.0.10+1
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.3
  geocoding: ^2.2.2
  geolocator: ^10.1.1
  flutter_typeahead: ^4.8.0
  marquee: ^2.2.3
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.14.11
  # fluttertoast: ^8.2.4
  permission_handler: ^11.3.0
  flutter_downloader: ^1.11.6
  dropdown_search: ^5.0.6
  flutter_inappwebview: ^6.0.0
  path: ^1.9.0
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2
  intl: ^0.20.2
  # sign_in_with_apple: ^5.0.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  just_audio: ^0.9.36
  # file_picker: ^6.2.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.12.0
  dropdown_button2: ^2.3.9
  gradient_borders: ^1.0.0
  firebase_auth: ^4.20.0


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
dependency_overrides:
  flutter_keyboard_visibility: ^6.0.0

